from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Team',
    'Challenge',
    'Solve',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Team': {
        'solves': 'Solve',
    },
    'Challenge': {
        'solves': 'Solve',
    },
    'Solve': {
        'team': 'Team',
        'challenge': 'Challenge',
    },
}

# fmt: on