# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Team types

class TeamOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Team create method"""
    id: _int
    score: _int
    solves: 'SolveCreateManyNestedWithoutRelationsInput'


class TeamCreateInput(TeamOptionalCreateInput):
    """Required arguments to the Team create method"""
    name: _str
    email: _str
    password_hash: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class TeamOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Team create method, without relations"""
    id: _int
    score: _int


class TeamCreateWithoutRelationsInput(TeamOptionalCreateWithoutRelationsInput):
    """Required arguments to the Team create method, without relations"""
    name: _str
    email: _str
    password_hash: _str

class TeamConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'TeamCreateWithoutRelationsInput'
    where: 'TeamWhereUniqueInput'

class TeamCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'TeamCreateWithoutRelationsInput'
    connect: 'TeamWhereUniqueInput'
    connect_or_create: 'TeamConnectOrCreateWithoutRelationsInput'


class TeamCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['TeamCreateWithoutRelationsInput', List['TeamCreateWithoutRelationsInput']]
    connect: Union['TeamWhereUniqueInput', List['TeamWhereUniqueInput']]
    connect_or_create: Union['TeamConnectOrCreateWithoutRelationsInput', List['TeamConnectOrCreateWithoutRelationsInput']]

_TeamWhereUnique_id_Input = TypedDict(
    '_TeamWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

_TeamWhereUnique_name_Input = TypedDict(
    '_TeamWhereUnique_name_Input',
    {
        'name': '_str',
    },
    total=True
)

_TeamWhereUnique_email_Input = TypedDict(
    '_TeamWhereUnique_email_Input',
    {
        'email': '_str',
    },
    total=True
)

TeamWhereUniqueInput = Union[
    '_TeamWhereUnique_id_Input',
    '_TeamWhereUnique_name_Input',
    '_TeamWhereUnique_email_Input',
]


class TeamUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    name: _str
    email: _str
    password_hash: _str
    score: Union[AtomicIntInput, _int]
    solves: 'SolveUpdateManyWithoutRelationsInput'


class TeamUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    name: _str
    email: _str
    password_hash: _str
    score: Union[AtomicIntInput, _int]


class TeamUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['TeamCreateWithoutRelationsInput']
    connect: List['TeamWhereUniqueInput']
    connect_or_create: List['TeamConnectOrCreateWithoutRelationsInput']
    set: List['TeamWhereUniqueInput']
    disconnect: List['TeamWhereUniqueInput']
    delete: List['TeamWhereUniqueInput']

    # TODO
    # update: List['TeamUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['TeamUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['TeamScalarWhereInput']
    # upsert: List['TeamUpserteWithWhereUniqueWithoutRelationsInput']


class TeamUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'TeamCreateWithoutRelationsInput'
    connect: 'TeamWhereUniqueInput'
    connect_or_create: 'TeamConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'TeamUpdateInput'
    # upsert: 'TeamUpsertWithoutRelationsInput'


class TeamUpsertInput(TypedDict):
    create: 'TeamCreateInput'
    update: 'TeamUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Team_id_OrderByInput = TypedDict(
    '_Team_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Team_name_OrderByInput = TypedDict(
    '_Team_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_Team_email_OrderByInput = TypedDict(
    '_Team_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_Team_password_hash_OrderByInput = TypedDict(
    '_Team_password_hash_OrderByInput',
    {
        'password_hash': 'SortOrder',
    },
    total=True
)

_Team_score_OrderByInput = TypedDict(
    '_Team_score_OrderByInput',
    {
        'score': 'SortOrder',
    },
    total=True
)

_Team_RelevanceInner = TypedDict(
    '_Team_RelevanceInner',
    {
        'fields': 'List[TeamScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Team_RelevanceOrderByInput = TypedDict(
    '_Team_RelevanceOrderByInput',
    {
        '_relevance': '_Team_RelevanceInner',
    },
    total=True
)

TeamOrderByInput = Union[
    '_Team_id_OrderByInput',
    '_Team_name_OrderByInput',
    '_Team_email_OrderByInput',
    '_Team_password_hash_OrderByInput',
    '_Team_score_OrderByInput',
    '_Team_RelevanceOrderByInput',
]



# recursive Team types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

TeamRelationFilter = TypedDict(
    'TeamRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class TeamListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class TeamInclude(TypedDict, total=False):
    """Team relational arguments"""
    solves: Union[bool, 'FindManySolveArgsFromTeam']


    

class TeamIncludeFromTeam(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive1']


class TeamIncludeFromTeamRecursive1(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive2']


class TeamIncludeFromTeamRecursive2(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive3']


class TeamIncludeFromTeamRecursive3(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive4']


class TeamIncludeFromTeamRecursive4(TypedDict, total=False):
    """Relational arguments for Team"""

    

class TeamArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    include: 'TeamIncludeFromTeamRecursive1'


class TeamArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    include: 'TeamIncludeFromTeamRecursive2'


class TeamArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    include: 'TeamIncludeFromTeamRecursive3'


class TeamArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    include: 'TeamIncludeFromTeamRecursive4'


class TeamArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    
    

class FindManyTeamArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive1'


class FindManyTeamArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive2'


class FindManyTeamArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive3'


class FindManyTeamArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive4'


class FindManyTeamArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    
    

class ChallengeIncludeFromTeam(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive1']


class ChallengeIncludeFromTeamRecursive1(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive2']


class ChallengeIncludeFromTeamRecursive2(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive3']


class ChallengeIncludeFromTeamRecursive3(TypedDict, total=False):
    """Relational arguments for Team"""
    solves: Union[bool, 'FindManySolveArgsFromTeamRecursive4']


class ChallengeIncludeFromTeamRecursive4(TypedDict, total=False):
    """Relational arguments for Team"""

    

class ChallengeArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    include: 'ChallengeIncludeFromChallengeRecursive1'


class ChallengeArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    include: 'ChallengeIncludeFromChallengeRecursive2'


class ChallengeArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    include: 'ChallengeIncludeFromChallengeRecursive3'


class ChallengeArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    include: 'ChallengeIncludeFromChallengeRecursive4'


class ChallengeArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    
    

class FindManyChallengeArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive1'


class FindManyChallengeArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive2'


class FindManyChallengeArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive3'


class FindManyChallengeArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive4'


class FindManyChallengeArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    
    

class SolveIncludeFromTeam(TypedDict, total=False):
    """Relational arguments for Team"""
    team: Union[bool, 'TeamArgsFromTeamRecursive1']
    challenge: Union[bool, 'ChallengeArgsFromTeamRecursive1']


class SolveIncludeFromTeamRecursive1(TypedDict, total=False):
    """Relational arguments for Team"""
    team: Union[bool, 'TeamArgsFromTeamRecursive2']
    challenge: Union[bool, 'ChallengeArgsFromTeamRecursive2']


class SolveIncludeFromTeamRecursive2(TypedDict, total=False):
    """Relational arguments for Team"""
    team: Union[bool, 'TeamArgsFromTeamRecursive3']
    challenge: Union[bool, 'ChallengeArgsFromTeamRecursive3']


class SolveIncludeFromTeamRecursive3(TypedDict, total=False):
    """Relational arguments for Team"""
    team: Union[bool, 'TeamArgsFromTeamRecursive4']
    challenge: Union[bool, 'ChallengeArgsFromTeamRecursive4']


class SolveIncludeFromTeamRecursive4(TypedDict, total=False):
    """Relational arguments for Team"""

    

class SolveArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    include: 'SolveIncludeFromSolveRecursive1'


class SolveArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    include: 'SolveIncludeFromSolveRecursive2'


class SolveArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    include: 'SolveIncludeFromSolveRecursive3'


class SolveArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    include: 'SolveIncludeFromSolveRecursive4'


class SolveArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    
    

class FindManySolveArgsFromTeam(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive1'


class FindManySolveArgsFromTeamRecursive1(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive2'


class FindManySolveArgsFromTeamRecursive2(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive3'


class FindManySolveArgsFromTeamRecursive3(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive4'


class FindManySolveArgsFromTeamRecursive4(TypedDict, total=False):
    """Arguments for Team"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    


FindManyTeamArgs = FindManyTeamArgsFromTeam
FindFirstTeamArgs = FindManyTeamArgsFromTeam


    

class TeamWhereInput(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password_hash: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['TeamWhereInputRecursive1', List['TeamWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['TeamWhereInputRecursive1']
    OR: List['TeamWhereInputRecursive1']
    NOT: List['TeamWhereInputRecursive1']


class TeamWhereInputRecursive1(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password_hash: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['TeamWhereInputRecursive2', List['TeamWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['TeamWhereInputRecursive2']
    OR: List['TeamWhereInputRecursive2']
    NOT: List['TeamWhereInputRecursive2']


class TeamWhereInputRecursive2(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password_hash: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['TeamWhereInputRecursive3', List['TeamWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['TeamWhereInputRecursive3']
    OR: List['TeamWhereInputRecursive3']
    NOT: List['TeamWhereInputRecursive3']


class TeamWhereInputRecursive3(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password_hash: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['TeamWhereInputRecursive4', List['TeamWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['TeamWhereInputRecursive4']
    OR: List['TeamWhereInputRecursive4']
    NOT: List['TeamWhereInputRecursive4']


class TeamWhereInputRecursive4(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password_hash: Union[_str, 'types.StringFilter']
    score: Union[_int, 'types.IntFilter']
    solves: 'SolveListRelationFilter'



# aggregate Team types


    

class TeamScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password_hash: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['TeamScalarWhereWithAggregatesInputRecursive1']
    OR: List['TeamScalarWhereWithAggregatesInputRecursive1']
    NOT: List['TeamScalarWhereWithAggregatesInputRecursive1']


class TeamScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password_hash: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['TeamScalarWhereWithAggregatesInputRecursive2']
    OR: List['TeamScalarWhereWithAggregatesInputRecursive2']
    NOT: List['TeamScalarWhereWithAggregatesInputRecursive2']


class TeamScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password_hash: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['TeamScalarWhereWithAggregatesInputRecursive3']
    OR: List['TeamScalarWhereWithAggregatesInputRecursive3']
    NOT: List['TeamScalarWhereWithAggregatesInputRecursive3']


class TeamScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password_hash: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['TeamScalarWhereWithAggregatesInputRecursive4']
    OR: List['TeamScalarWhereWithAggregatesInputRecursive4']
    NOT: List['TeamScalarWhereWithAggregatesInputRecursive4']


class TeamScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Team arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password_hash: Union[_str, 'types.StringWithAggregatesFilter']
    score: Union[_int, 'types.IntWithAggregatesFilter']



class TeamGroupByOutput(TypedDict, total=False):
    id: _int
    name: _str
    email: _str
    password_hash: _str
    score: _int
    _sum: 'TeamSumAggregateOutput'
    _avg: 'TeamAvgAggregateOutput'
    _min: 'TeamMinAggregateOutput'
    _max: 'TeamMaxAggregateOutput'
    _count: 'TeamCountAggregateOutput'


class TeamAvgAggregateOutput(TypedDict, total=False):
    """Team output for aggregating averages"""
    id: float
    score: float


class TeamSumAggregateOutput(TypedDict, total=False):
    """Team output for aggregating sums"""
    id: _int
    score: _int


class TeamScalarAggregateOutput(TypedDict, total=False):
    """Team output including scalar fields"""
    id: _int
    name: _str
    email: _str
    password_hash: _str
    score: _int


TeamMinAggregateOutput = TeamScalarAggregateOutput
TeamMaxAggregateOutput = TeamScalarAggregateOutput


class TeamMaxAggregateInput(TypedDict, total=False):
    """Team input for aggregating by max"""
    id: bool
    name: bool
    email: bool
    password_hash: bool
    score: bool


class TeamMinAggregateInput(TypedDict, total=False):
    """Team input for aggregating by min"""
    id: bool
    name: bool
    email: bool
    password_hash: bool
    score: bool


class TeamNumberAggregateInput(TypedDict, total=False):
    """Team input for aggregating numbers"""
    id: bool
    score: bool


TeamAvgAggregateInput = TeamNumberAggregateInput
TeamSumAggregateInput = TeamNumberAggregateInput


TeamCountAggregateInput = TypedDict(
    'TeamCountAggregateInput',
    {
        'id': bool,
        'name': bool,
        'email': bool,
        'password_hash': bool,
        'score': bool,
        '_all': bool,
    },
    total=False,
)

TeamCountAggregateOutput = TypedDict(
    'TeamCountAggregateOutput',
    {
        'id': int,
        'name': int,
        'email': int,
        'password_hash': int,
        'score': int,
        '_all': int,
    },
    total=False,
)


TeamKeys = Literal[
    'id',
    'name',
    'email',
    'password_hash',
    'score',
    'solves',
]
TeamScalarFieldKeys = Literal[
    'id',
    'name',
    'email',
    'password_hash',
    'score',
]
TeamScalarFieldKeysT = TypeVar('TeamScalarFieldKeysT', bound=TeamScalarFieldKeys)

TeamRelationalFieldKeys = Literal[
        'solves',
    ]

# Challenge types

class ChallengeOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Challenge create method"""
    id: _int
    file_url: Optional[_str]
    solves: 'SolveCreateManyNestedWithoutRelationsInput'


class ChallengeCreateInput(ChallengeOptionalCreateInput):
    """Required arguments to the Challenge create method"""
    title: _str
    category: _str
    difficulty: _str
    points: _int
    description: _str
    flag: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class ChallengeOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Challenge create method, without relations"""
    id: _int
    file_url: Optional[_str]


class ChallengeCreateWithoutRelationsInput(ChallengeOptionalCreateWithoutRelationsInput):
    """Required arguments to the Challenge create method, without relations"""
    title: _str
    category: _str
    difficulty: _str
    points: _int
    description: _str
    flag: _str

class ChallengeConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'ChallengeCreateWithoutRelationsInput'
    where: 'ChallengeWhereUniqueInput'

class ChallengeCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'ChallengeCreateWithoutRelationsInput'
    connect: 'ChallengeWhereUniqueInput'
    connect_or_create: 'ChallengeConnectOrCreateWithoutRelationsInput'


class ChallengeCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['ChallengeCreateWithoutRelationsInput', List['ChallengeCreateWithoutRelationsInput']]
    connect: Union['ChallengeWhereUniqueInput', List['ChallengeWhereUniqueInput']]
    connect_or_create: Union['ChallengeConnectOrCreateWithoutRelationsInput', List['ChallengeConnectOrCreateWithoutRelationsInput']]

_ChallengeWhereUnique_id_Input = TypedDict(
    '_ChallengeWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

ChallengeWhereUniqueInput = _ChallengeWhereUnique_id_Input


class ChallengeUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    title: _str
    category: _str
    difficulty: _str
    points: Union[AtomicIntInput, _int]
    description: _str
    file_url: Optional[_str]
    flag: _str
    solves: 'SolveUpdateManyWithoutRelationsInput'


class ChallengeUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    title: _str
    category: _str
    difficulty: _str
    points: Union[AtomicIntInput, _int]
    description: _str
    file_url: Optional[_str]
    flag: _str


class ChallengeUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['ChallengeCreateWithoutRelationsInput']
    connect: List['ChallengeWhereUniqueInput']
    connect_or_create: List['ChallengeConnectOrCreateWithoutRelationsInput']
    set: List['ChallengeWhereUniqueInput']
    disconnect: List['ChallengeWhereUniqueInput']
    delete: List['ChallengeWhereUniqueInput']

    # TODO
    # update: List['ChallengeUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['ChallengeUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['ChallengeScalarWhereInput']
    # upsert: List['ChallengeUpserteWithWhereUniqueWithoutRelationsInput']


class ChallengeUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'ChallengeCreateWithoutRelationsInput'
    connect: 'ChallengeWhereUniqueInput'
    connect_or_create: 'ChallengeConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'ChallengeUpdateInput'
    # upsert: 'ChallengeUpsertWithoutRelationsInput'


class ChallengeUpsertInput(TypedDict):
    create: 'ChallengeCreateInput'
    update: 'ChallengeUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Challenge_id_OrderByInput = TypedDict(
    '_Challenge_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Challenge_title_OrderByInput = TypedDict(
    '_Challenge_title_OrderByInput',
    {
        'title': 'SortOrder',
    },
    total=True
)

_Challenge_category_OrderByInput = TypedDict(
    '_Challenge_category_OrderByInput',
    {
        'category': 'SortOrder',
    },
    total=True
)

_Challenge_difficulty_OrderByInput = TypedDict(
    '_Challenge_difficulty_OrderByInput',
    {
        'difficulty': 'SortOrder',
    },
    total=True
)

_Challenge_points_OrderByInput = TypedDict(
    '_Challenge_points_OrderByInput',
    {
        'points': 'SortOrder',
    },
    total=True
)

_Challenge_description_OrderByInput = TypedDict(
    '_Challenge_description_OrderByInput',
    {
        'description': 'SortOrder',
    },
    total=True
)

_Challenge_file_url_OrderByInput = TypedDict(
    '_Challenge_file_url_OrderByInput',
    {
        'file_url': 'SortOrder',
    },
    total=True
)

_Challenge_flag_OrderByInput = TypedDict(
    '_Challenge_flag_OrderByInput',
    {
        'flag': 'SortOrder',
    },
    total=True
)

_Challenge_RelevanceInner = TypedDict(
    '_Challenge_RelevanceInner',
    {
        'fields': 'List[ChallengeScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Challenge_RelevanceOrderByInput = TypedDict(
    '_Challenge_RelevanceOrderByInput',
    {
        '_relevance': '_Challenge_RelevanceInner',
    },
    total=True
)

ChallengeOrderByInput = Union[
    '_Challenge_id_OrderByInput',
    '_Challenge_title_OrderByInput',
    '_Challenge_category_OrderByInput',
    '_Challenge_difficulty_OrderByInput',
    '_Challenge_points_OrderByInput',
    '_Challenge_description_OrderByInput',
    '_Challenge_file_url_OrderByInput',
    '_Challenge_flag_OrderByInput',
    '_Challenge_RelevanceOrderByInput',
]



# recursive Challenge types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

ChallengeRelationFilter = TypedDict(
    'ChallengeRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class ChallengeListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class ChallengeInclude(TypedDict, total=False):
    """Challenge relational arguments"""
    solves: Union[bool, 'FindManySolveArgsFromChallenge']


    

class TeamIncludeFromChallenge(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive1']


class TeamIncludeFromChallengeRecursive1(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive2']


class TeamIncludeFromChallengeRecursive2(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive3']


class TeamIncludeFromChallengeRecursive3(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive4']


class TeamIncludeFromChallengeRecursive4(TypedDict, total=False):
    """Relational arguments for Challenge"""

    

class TeamArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'TeamIncludeFromTeamRecursive1'


class TeamArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'TeamIncludeFromTeamRecursive2'


class TeamArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'TeamIncludeFromTeamRecursive3'


class TeamArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'TeamIncludeFromTeamRecursive4'


class TeamArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    
    

class FindManyTeamArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive1'


class FindManyTeamArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive2'


class FindManyTeamArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive3'


class FindManyTeamArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive4'


class FindManyTeamArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    
    

class ChallengeIncludeFromChallenge(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive1']


class ChallengeIncludeFromChallengeRecursive1(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive2']


class ChallengeIncludeFromChallengeRecursive2(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive3']


class ChallengeIncludeFromChallengeRecursive3(TypedDict, total=False):
    """Relational arguments for Challenge"""
    solves: Union[bool, 'FindManySolveArgsFromChallengeRecursive4']


class ChallengeIncludeFromChallengeRecursive4(TypedDict, total=False):
    """Relational arguments for Challenge"""

    

class ChallengeArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'ChallengeIncludeFromChallengeRecursive1'


class ChallengeArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'ChallengeIncludeFromChallengeRecursive2'


class ChallengeArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'ChallengeIncludeFromChallengeRecursive3'


class ChallengeArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'ChallengeIncludeFromChallengeRecursive4'


class ChallengeArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    
    

class FindManyChallengeArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive1'


class FindManyChallengeArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive2'


class FindManyChallengeArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive3'


class FindManyChallengeArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive4'


class FindManyChallengeArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    
    

class SolveIncludeFromChallenge(TypedDict, total=False):
    """Relational arguments for Challenge"""
    team: Union[bool, 'TeamArgsFromChallengeRecursive1']
    challenge: Union[bool, 'ChallengeArgsFromChallengeRecursive1']


class SolveIncludeFromChallengeRecursive1(TypedDict, total=False):
    """Relational arguments for Challenge"""
    team: Union[bool, 'TeamArgsFromChallengeRecursive2']
    challenge: Union[bool, 'ChallengeArgsFromChallengeRecursive2']


class SolveIncludeFromChallengeRecursive2(TypedDict, total=False):
    """Relational arguments for Challenge"""
    team: Union[bool, 'TeamArgsFromChallengeRecursive3']
    challenge: Union[bool, 'ChallengeArgsFromChallengeRecursive3']


class SolveIncludeFromChallengeRecursive3(TypedDict, total=False):
    """Relational arguments for Challenge"""
    team: Union[bool, 'TeamArgsFromChallengeRecursive4']
    challenge: Union[bool, 'ChallengeArgsFromChallengeRecursive4']


class SolveIncludeFromChallengeRecursive4(TypedDict, total=False):
    """Relational arguments for Challenge"""

    

class SolveArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'SolveIncludeFromSolveRecursive1'


class SolveArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'SolveIncludeFromSolveRecursive2'


class SolveArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'SolveIncludeFromSolveRecursive3'


class SolveArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    include: 'SolveIncludeFromSolveRecursive4'


class SolveArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    
    

class FindManySolveArgsFromChallenge(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive1'


class FindManySolveArgsFromChallengeRecursive1(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive2'


class FindManySolveArgsFromChallengeRecursive2(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive3'


class FindManySolveArgsFromChallengeRecursive3(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive4'


class FindManySolveArgsFromChallengeRecursive4(TypedDict, total=False):
    """Arguments for Challenge"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    


FindManyChallengeArgs = FindManyChallengeArgsFromChallenge
FindFirstChallengeArgs = FindManyChallengeArgsFromChallenge


    

class ChallengeWhereInput(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    category: Union[_str, 'types.StringFilter']
    difficulty: Union[_str, 'types.StringFilter']
    points: Union[_int, 'types.IntFilter']
    description: Union[_str, 'types.StringFilter']
    file_url: Union[None, _str, 'types.StringFilter']
    flag: Union[_str, 'types.StringFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['ChallengeWhereInputRecursive1', List['ChallengeWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['ChallengeWhereInputRecursive1']
    OR: List['ChallengeWhereInputRecursive1']
    NOT: List['ChallengeWhereInputRecursive1']


class ChallengeWhereInputRecursive1(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    category: Union[_str, 'types.StringFilter']
    difficulty: Union[_str, 'types.StringFilter']
    points: Union[_int, 'types.IntFilter']
    description: Union[_str, 'types.StringFilter']
    file_url: Union[None, _str, 'types.StringFilter']
    flag: Union[_str, 'types.StringFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['ChallengeWhereInputRecursive2', List['ChallengeWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['ChallengeWhereInputRecursive2']
    OR: List['ChallengeWhereInputRecursive2']
    NOT: List['ChallengeWhereInputRecursive2']


class ChallengeWhereInputRecursive2(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    category: Union[_str, 'types.StringFilter']
    difficulty: Union[_str, 'types.StringFilter']
    points: Union[_int, 'types.IntFilter']
    description: Union[_str, 'types.StringFilter']
    file_url: Union[None, _str, 'types.StringFilter']
    flag: Union[_str, 'types.StringFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['ChallengeWhereInputRecursive3', List['ChallengeWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['ChallengeWhereInputRecursive3']
    OR: List['ChallengeWhereInputRecursive3']
    NOT: List['ChallengeWhereInputRecursive3']


class ChallengeWhereInputRecursive3(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    category: Union[_str, 'types.StringFilter']
    difficulty: Union[_str, 'types.StringFilter']
    points: Union[_int, 'types.IntFilter']
    description: Union[_str, 'types.StringFilter']
    file_url: Union[None, _str, 'types.StringFilter']
    flag: Union[_str, 'types.StringFilter']
    solves: 'SolveListRelationFilter'

    # should be noted that AND and NOT should be Union['ChallengeWhereInputRecursive4', List['ChallengeWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['ChallengeWhereInputRecursive4']
    OR: List['ChallengeWhereInputRecursive4']
    NOT: List['ChallengeWhereInputRecursive4']


class ChallengeWhereInputRecursive4(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    category: Union[_str, 'types.StringFilter']
    difficulty: Union[_str, 'types.StringFilter']
    points: Union[_int, 'types.IntFilter']
    description: Union[_str, 'types.StringFilter']
    file_url: Union[None, _str, 'types.StringFilter']
    flag: Union[_str, 'types.StringFilter']
    solves: 'SolveListRelationFilter'



# aggregate Challenge types


    

class ChallengeScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    difficulty: Union[_str, 'types.StringWithAggregatesFilter']
    points: Union[_int, 'types.IntWithAggregatesFilter']
    description: Union[_str, 'types.StringWithAggregatesFilter']
    file_url: Union[_str, 'types.StringWithAggregatesFilter']
    flag: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ChallengeScalarWhereWithAggregatesInputRecursive1']
    OR: List['ChallengeScalarWhereWithAggregatesInputRecursive1']
    NOT: List['ChallengeScalarWhereWithAggregatesInputRecursive1']


class ChallengeScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    difficulty: Union[_str, 'types.StringWithAggregatesFilter']
    points: Union[_int, 'types.IntWithAggregatesFilter']
    description: Union[_str, 'types.StringWithAggregatesFilter']
    file_url: Union[_str, 'types.StringWithAggregatesFilter']
    flag: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ChallengeScalarWhereWithAggregatesInputRecursive2']
    OR: List['ChallengeScalarWhereWithAggregatesInputRecursive2']
    NOT: List['ChallengeScalarWhereWithAggregatesInputRecursive2']


class ChallengeScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    difficulty: Union[_str, 'types.StringWithAggregatesFilter']
    points: Union[_int, 'types.IntWithAggregatesFilter']
    description: Union[_str, 'types.StringWithAggregatesFilter']
    file_url: Union[_str, 'types.StringWithAggregatesFilter']
    flag: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ChallengeScalarWhereWithAggregatesInputRecursive3']
    OR: List['ChallengeScalarWhereWithAggregatesInputRecursive3']
    NOT: List['ChallengeScalarWhereWithAggregatesInputRecursive3']


class ChallengeScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    difficulty: Union[_str, 'types.StringWithAggregatesFilter']
    points: Union[_int, 'types.IntWithAggregatesFilter']
    description: Union[_str, 'types.StringWithAggregatesFilter']
    file_url: Union[_str, 'types.StringWithAggregatesFilter']
    flag: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['ChallengeScalarWhereWithAggregatesInputRecursive4']
    OR: List['ChallengeScalarWhereWithAggregatesInputRecursive4']
    NOT: List['ChallengeScalarWhereWithAggregatesInputRecursive4']


class ChallengeScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Challenge arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    category: Union[_str, 'types.StringWithAggregatesFilter']
    difficulty: Union[_str, 'types.StringWithAggregatesFilter']
    points: Union[_int, 'types.IntWithAggregatesFilter']
    description: Union[_str, 'types.StringWithAggregatesFilter']
    file_url: Union[_str, 'types.StringWithAggregatesFilter']
    flag: Union[_str, 'types.StringWithAggregatesFilter']



class ChallengeGroupByOutput(TypedDict, total=False):
    id: _int
    title: _str
    category: _str
    difficulty: _str
    points: _int
    description: _str
    file_url: _str
    flag: _str
    _sum: 'ChallengeSumAggregateOutput'
    _avg: 'ChallengeAvgAggregateOutput'
    _min: 'ChallengeMinAggregateOutput'
    _max: 'ChallengeMaxAggregateOutput'
    _count: 'ChallengeCountAggregateOutput'


class ChallengeAvgAggregateOutput(TypedDict, total=False):
    """Challenge output for aggregating averages"""
    id: float
    points: float


class ChallengeSumAggregateOutput(TypedDict, total=False):
    """Challenge output for aggregating sums"""
    id: _int
    points: _int


class ChallengeScalarAggregateOutput(TypedDict, total=False):
    """Challenge output including scalar fields"""
    id: _int
    title: _str
    category: _str
    difficulty: _str
    points: _int
    description: _str
    file_url: _str
    flag: _str


ChallengeMinAggregateOutput = ChallengeScalarAggregateOutput
ChallengeMaxAggregateOutput = ChallengeScalarAggregateOutput


class ChallengeMaxAggregateInput(TypedDict, total=False):
    """Challenge input for aggregating by max"""
    id: bool
    title: bool
    category: bool
    difficulty: bool
    points: bool
    description: bool
    file_url: bool
    flag: bool


class ChallengeMinAggregateInput(TypedDict, total=False):
    """Challenge input for aggregating by min"""
    id: bool
    title: bool
    category: bool
    difficulty: bool
    points: bool
    description: bool
    file_url: bool
    flag: bool


class ChallengeNumberAggregateInput(TypedDict, total=False):
    """Challenge input for aggregating numbers"""
    id: bool
    points: bool


ChallengeAvgAggregateInput = ChallengeNumberAggregateInput
ChallengeSumAggregateInput = ChallengeNumberAggregateInput


ChallengeCountAggregateInput = TypedDict(
    'ChallengeCountAggregateInput',
    {
        'id': bool,
        'title': bool,
        'category': bool,
        'difficulty': bool,
        'points': bool,
        'description': bool,
        'file_url': bool,
        'flag': bool,
        '_all': bool,
    },
    total=False,
)

ChallengeCountAggregateOutput = TypedDict(
    'ChallengeCountAggregateOutput',
    {
        'id': int,
        'title': int,
        'category': int,
        'difficulty': int,
        'points': int,
        'description': int,
        'file_url': int,
        'flag': int,
        '_all': int,
    },
    total=False,
)


ChallengeKeys = Literal[
    'id',
    'title',
    'category',
    'difficulty',
    'points',
    'description',
    'file_url',
    'flag',
    'solves',
]
ChallengeScalarFieldKeys = Literal[
    'id',
    'title',
    'category',
    'difficulty',
    'points',
    'description',
    'file_url',
    'flag',
]
ChallengeScalarFieldKeysT = TypeVar('ChallengeScalarFieldKeysT', bound=ChallengeScalarFieldKeys)

ChallengeRelationalFieldKeys = Literal[
        'solves',
    ]

# Solve types

class SolveOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Solve create method"""
    id: _int
    team: 'TeamCreateNestedWithoutRelationsInput'
    team_id: _int
    challenge: 'ChallengeCreateNestedWithoutRelationsInput'
    challenge_id: _int


class SolveCreateInput(SolveOptionalCreateInput):
    """Required arguments to the Solve create method"""


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class SolveOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Solve create method, without relations"""
    id: _int
    team_id: _int
    challenge_id: _int


class SolveCreateWithoutRelationsInput(SolveOptionalCreateWithoutRelationsInput):
    """Required arguments to the Solve create method, without relations"""

class SolveConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'SolveCreateWithoutRelationsInput'
    where: 'SolveWhereUniqueInput'

class SolveCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'SolveCreateWithoutRelationsInput'
    connect: 'SolveWhereUniqueInput'
    connect_or_create: 'SolveConnectOrCreateWithoutRelationsInput'


class SolveCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['SolveCreateWithoutRelationsInput', List['SolveCreateWithoutRelationsInput']]
    connect: Union['SolveWhereUniqueInput', List['SolveWhereUniqueInput']]
    connect_or_create: Union['SolveConnectOrCreateWithoutRelationsInput', List['SolveConnectOrCreateWithoutRelationsInput']]

_SolveWhereUnique_id_Input = TypedDict(
    '_SolveWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

_SolveCompoundteam_id_challenge_idKeyInner = TypedDict(
    '_SolveCompoundteam_id_challenge_idKeyInner',
    {
        'team_id': '_int',
        'challenge_id': '_int',
    },
    total=True
)

_SolveCompoundteam_id_challenge_idKey = TypedDict(
    '_SolveCompoundteam_id_challenge_idKey',
    {
        'team_id_challenge_id': '_SolveCompoundteam_id_challenge_idKeyInner',
    },
    total=True
)

SolveWhereUniqueInput = Union[
    '_SolveWhereUnique_id_Input',
    '_SolveCompoundteam_id_challenge_idKey',
]


class SolveUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    team: 'TeamUpdateOneWithoutRelationsInput'
    challenge: 'ChallengeUpdateOneWithoutRelationsInput'


class SolveUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]


class SolveUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['SolveCreateWithoutRelationsInput']
    connect: List['SolveWhereUniqueInput']
    connect_or_create: List['SolveConnectOrCreateWithoutRelationsInput']
    set: List['SolveWhereUniqueInput']
    disconnect: List['SolveWhereUniqueInput']
    delete: List['SolveWhereUniqueInput']

    # TODO
    # update: List['SolveUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['SolveUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['SolveScalarWhereInput']
    # upsert: List['SolveUpserteWithWhereUniqueWithoutRelationsInput']


class SolveUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'SolveCreateWithoutRelationsInput'
    connect: 'SolveWhereUniqueInput'
    connect_or_create: 'SolveConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'SolveUpdateInput'
    # upsert: 'SolveUpsertWithoutRelationsInput'


class SolveUpsertInput(TypedDict):
    create: 'SolveCreateInput'
    update: 'SolveUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Solve_id_OrderByInput = TypedDict(
    '_Solve_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Solve_team_id_OrderByInput = TypedDict(
    '_Solve_team_id_OrderByInput',
    {
        'team_id': 'SortOrder',
    },
    total=True
)

_Solve_challenge_id_OrderByInput = TypedDict(
    '_Solve_challenge_id_OrderByInput',
    {
        'challenge_id': 'SortOrder',
    },
    total=True
)

_Solve_RelevanceInner = TypedDict(
    '_Solve_RelevanceInner',
    {
        'fields': 'List[SolveScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_Solve_RelevanceOrderByInput = TypedDict(
    '_Solve_RelevanceOrderByInput',
    {
        '_relevance': '_Solve_RelevanceInner',
    },
    total=True
)

SolveOrderByInput = Union[
    '_Solve_id_OrderByInput',
    '_Solve_team_id_OrderByInput',
    '_Solve_challenge_id_OrderByInput',
    '_Solve_RelevanceOrderByInput',
]



# recursive Solve types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

SolveRelationFilter = TypedDict(
    'SolveRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class SolveListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class SolveInclude(TypedDict, total=False):
    """Solve relational arguments"""
    team: Union[bool, 'TeamArgsFromSolve']
    challenge: Union[bool, 'ChallengeArgsFromSolve']


    

class TeamIncludeFromSolve(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive1']


class TeamIncludeFromSolveRecursive1(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive2']


class TeamIncludeFromSolveRecursive2(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive3']


class TeamIncludeFromSolveRecursive3(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive4']


class TeamIncludeFromSolveRecursive4(TypedDict, total=False):
    """Relational arguments for Solve"""

    

class TeamArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'TeamIncludeFromTeamRecursive1'


class TeamArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'TeamIncludeFromTeamRecursive2'


class TeamArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'TeamIncludeFromTeamRecursive3'


class TeamArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'TeamIncludeFromTeamRecursive4'


class TeamArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    
    

class FindManyTeamArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive1'


class FindManyTeamArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive2'


class FindManyTeamArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive3'


class FindManyTeamArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    include: 'TeamIncludeFromTeamRecursive4'


class FindManyTeamArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['TeamOrderByInput', List['TeamOrderByInput']]
    where: 'TeamWhereInput'
    cursor: 'TeamWhereUniqueInput'
    distinct: List['TeamScalarFieldKeys']
    
    

class ChallengeIncludeFromSolve(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive1']


class ChallengeIncludeFromSolveRecursive1(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive2']


class ChallengeIncludeFromSolveRecursive2(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive3']


class ChallengeIncludeFromSolveRecursive3(TypedDict, total=False):
    """Relational arguments for Solve"""
    solves: Union[bool, 'FindManySolveArgsFromSolveRecursive4']


class ChallengeIncludeFromSolveRecursive4(TypedDict, total=False):
    """Relational arguments for Solve"""

    

class ChallengeArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'ChallengeIncludeFromChallengeRecursive1'


class ChallengeArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'ChallengeIncludeFromChallengeRecursive2'


class ChallengeArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'ChallengeIncludeFromChallengeRecursive3'


class ChallengeArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'ChallengeIncludeFromChallengeRecursive4'


class ChallengeArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    
    

class FindManyChallengeArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive1'


class FindManyChallengeArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive2'


class FindManyChallengeArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive3'


class FindManyChallengeArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    include: 'ChallengeIncludeFromChallengeRecursive4'


class FindManyChallengeArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['ChallengeOrderByInput', List['ChallengeOrderByInput']]
    where: 'ChallengeWhereInput'
    cursor: 'ChallengeWhereUniqueInput'
    distinct: List['ChallengeScalarFieldKeys']
    
    

class SolveIncludeFromSolve(TypedDict, total=False):
    """Relational arguments for Solve"""
    team: Union[bool, 'TeamArgsFromSolveRecursive1']
    challenge: Union[bool, 'ChallengeArgsFromSolveRecursive1']


class SolveIncludeFromSolveRecursive1(TypedDict, total=False):
    """Relational arguments for Solve"""
    team: Union[bool, 'TeamArgsFromSolveRecursive2']
    challenge: Union[bool, 'ChallengeArgsFromSolveRecursive2']


class SolveIncludeFromSolveRecursive2(TypedDict, total=False):
    """Relational arguments for Solve"""
    team: Union[bool, 'TeamArgsFromSolveRecursive3']
    challenge: Union[bool, 'ChallengeArgsFromSolveRecursive3']


class SolveIncludeFromSolveRecursive3(TypedDict, total=False):
    """Relational arguments for Solve"""
    team: Union[bool, 'TeamArgsFromSolveRecursive4']
    challenge: Union[bool, 'ChallengeArgsFromSolveRecursive4']


class SolveIncludeFromSolveRecursive4(TypedDict, total=False):
    """Relational arguments for Solve"""

    

class SolveArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'SolveIncludeFromSolveRecursive1'


class SolveArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'SolveIncludeFromSolveRecursive2'


class SolveArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'SolveIncludeFromSolveRecursive3'


class SolveArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    include: 'SolveIncludeFromSolveRecursive4'


class SolveArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    
    

class FindManySolveArgsFromSolve(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive1'


class FindManySolveArgsFromSolveRecursive1(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive2'


class FindManySolveArgsFromSolveRecursive2(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive3'


class FindManySolveArgsFromSolveRecursive3(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    include: 'SolveIncludeFromSolveRecursive4'


class FindManySolveArgsFromSolveRecursive4(TypedDict, total=False):
    """Arguments for Solve"""
    take: int
    skip: int
    order_by: Union['SolveOrderByInput', List['SolveOrderByInput']]
    where: 'SolveWhereInput'
    cursor: 'SolveWhereUniqueInput'
    distinct: List['SolveScalarFieldKeys']
    


FindManySolveArgs = FindManySolveArgsFromSolve
FindFirstSolveArgs = FindManySolveArgsFromSolve


    

class SolveWhereInput(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    team: 'TeamRelationFilter'
    team_id: Union[_int, 'types.IntFilter']
    challenge: 'ChallengeRelationFilter'
    challenge_id: Union[_int, 'types.IntFilter']

    # should be noted that AND and NOT should be Union['SolveWhereInputRecursive1', List['SolveWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['SolveWhereInputRecursive1']
    OR: List['SolveWhereInputRecursive1']
    NOT: List['SolveWhereInputRecursive1']


class SolveWhereInputRecursive1(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    team: 'TeamRelationFilter'
    team_id: Union[_int, 'types.IntFilter']
    challenge: 'ChallengeRelationFilter'
    challenge_id: Union[_int, 'types.IntFilter']

    # should be noted that AND and NOT should be Union['SolveWhereInputRecursive2', List['SolveWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['SolveWhereInputRecursive2']
    OR: List['SolveWhereInputRecursive2']
    NOT: List['SolveWhereInputRecursive2']


class SolveWhereInputRecursive2(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    team: 'TeamRelationFilter'
    team_id: Union[_int, 'types.IntFilter']
    challenge: 'ChallengeRelationFilter'
    challenge_id: Union[_int, 'types.IntFilter']

    # should be noted that AND and NOT should be Union['SolveWhereInputRecursive3', List['SolveWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['SolveWhereInputRecursive3']
    OR: List['SolveWhereInputRecursive3']
    NOT: List['SolveWhereInputRecursive3']


class SolveWhereInputRecursive3(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    team: 'TeamRelationFilter'
    team_id: Union[_int, 'types.IntFilter']
    challenge: 'ChallengeRelationFilter'
    challenge_id: Union[_int, 'types.IntFilter']

    # should be noted that AND and NOT should be Union['SolveWhereInputRecursive4', List['SolveWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['SolveWhereInputRecursive4']
    OR: List['SolveWhereInputRecursive4']
    NOT: List['SolveWhereInputRecursive4']


class SolveWhereInputRecursive4(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    team: 'TeamRelationFilter'
    team_id: Union[_int, 'types.IntFilter']
    challenge: 'ChallengeRelationFilter'
    challenge_id: Union[_int, 'types.IntFilter']



# aggregate Solve types


    

class SolveScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    team_id: Union[_int, 'types.IntWithAggregatesFilter']
    challenge_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['SolveScalarWhereWithAggregatesInputRecursive1']
    OR: List['SolveScalarWhereWithAggregatesInputRecursive1']
    NOT: List['SolveScalarWhereWithAggregatesInputRecursive1']


class SolveScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    team_id: Union[_int, 'types.IntWithAggregatesFilter']
    challenge_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['SolveScalarWhereWithAggregatesInputRecursive2']
    OR: List['SolveScalarWhereWithAggregatesInputRecursive2']
    NOT: List['SolveScalarWhereWithAggregatesInputRecursive2']


class SolveScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    team_id: Union[_int, 'types.IntWithAggregatesFilter']
    challenge_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['SolveScalarWhereWithAggregatesInputRecursive3']
    OR: List['SolveScalarWhereWithAggregatesInputRecursive3']
    NOT: List['SolveScalarWhereWithAggregatesInputRecursive3']


class SolveScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    team_id: Union[_int, 'types.IntWithAggregatesFilter']
    challenge_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['SolveScalarWhereWithAggregatesInputRecursive4']
    OR: List['SolveScalarWhereWithAggregatesInputRecursive4']
    NOT: List['SolveScalarWhereWithAggregatesInputRecursive4']


class SolveScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Solve arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    team_id: Union[_int, 'types.IntWithAggregatesFilter']
    challenge_id: Union[_int, 'types.IntWithAggregatesFilter']



class SolveGroupByOutput(TypedDict, total=False):
    id: _int
    team_id: _int
    challenge_id: _int
    _sum: 'SolveSumAggregateOutput'
    _avg: 'SolveAvgAggregateOutput'
    _min: 'SolveMinAggregateOutput'
    _max: 'SolveMaxAggregateOutput'
    _count: 'SolveCountAggregateOutput'


class SolveAvgAggregateOutput(TypedDict, total=False):
    """Solve output for aggregating averages"""
    id: float
    team_id: float
    challenge_id: float


class SolveSumAggregateOutput(TypedDict, total=False):
    """Solve output for aggregating sums"""
    id: _int
    team_id: _int
    challenge_id: _int


class SolveScalarAggregateOutput(TypedDict, total=False):
    """Solve output including scalar fields"""
    id: _int
    team_id: _int
    challenge_id: _int


SolveMinAggregateOutput = SolveScalarAggregateOutput
SolveMaxAggregateOutput = SolveScalarAggregateOutput


class SolveMaxAggregateInput(TypedDict, total=False):
    """Solve input for aggregating by max"""
    id: bool
    team_id: bool
    challenge_id: bool


class SolveMinAggregateInput(TypedDict, total=False):
    """Solve input for aggregating by min"""
    id: bool
    team_id: bool
    challenge_id: bool


class SolveNumberAggregateInput(TypedDict, total=False):
    """Solve input for aggregating numbers"""
    id: bool
    team_id: bool
    challenge_id: bool


SolveAvgAggregateInput = SolveNumberAggregateInput
SolveSumAggregateInput = SolveNumberAggregateInput


SolveCountAggregateInput = TypedDict(
    'SolveCountAggregateInput',
    {
        'id': bool,
        'team_id': bool,
        'challenge_id': bool,
        '_all': bool,
    },
    total=False,
)

SolveCountAggregateOutput = TypedDict(
    'SolveCountAggregateOutput',
    {
        'id': int,
        'team_id': int,
        'challenge_id': int,
        '_all': int,
    },
    total=False,
)


SolveKeys = Literal[
    'id',
    'team',
    'team_id',
    'challenge',
    'challenge_id',
]
SolveScalarFieldKeys = Literal[
    'id',
    'team_id',
    'challenge_id',
]
SolveScalarFieldKeysT = TypeVar('SolveScalarFieldKeysT', bound=SolveScalarFieldKeys)

SolveRelationalFieldKeys = Literal[
        'team',
        'challenge',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields